
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyrlrmczannlnnzgzxjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5cmxybWN6YW5ubG5uemd6eGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTkzNjksImV4cCI6MjA1OTE5NTM2OX0.gOoUxQuBkMO1HFIeCBQiaSqioisUZDAV_6nTMWHY9EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add debug logs to check if supabase client is initialized correctly
console.log("Supabase client initialized:", !!supabase);

// Log storage bucket information for debugging
supabase.storage.listBuckets().then((response) => {
  if (response.error) {
    console.error("Error listing buckets:", response.error);
  } else {
    console.log("Available storage buckets:", response.data);
  }
});
